name: shelter_occupancy
version: '1.0.0'

profile: shelter_occupancy

model-paths: ["models"]

models:
  shelter_occupancy:
    staging:
      +schema: SILVER
      +materialized: table
    serving:
      +schema: GOLD
      +materialized: table
